services:
  postgres:
    image: postgres:18
    container_name: asaflive-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asaflive
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql

  redis:
    image: redis:alpine
    container_name: asaflive-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes --requirepass "redisPasdss!@#"
