services:
  postgres:
    image: postgres:18
    container_name: asaflive-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asafpostgress724
      POSTGRES_DB: asaflive
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    # networks:
    #   - backend

  redis:
    image: redis:alpine
    container_name: asaflive-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    # networks:
    #   - backend
    command: redis-server --appendonly yes --requirepass "redisPasdss"


  livekit:
    image: livekit/livekit-server:v1.13.3
    container_name: asaflive-livekit
    restart: always
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    # This binds all LiveKit ports directly to the host OS
    network_mode: host
    depends_on:
      - redis


  egress:
    image: livekit/egress:v1.10
    deploy:
      resources:
        limits:
          cpus: '4.0'       # Maximum CPU cores this container can use
          memory: 8G        # Maximum memory (Hard limit, container is killed if it exceeds this)
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN # کروم بدون این کار نمی‌کند
    security_opt:
      - seccomp=unconfined # غیرفعال کردن محدودیت‌های سیستم‌کال برای کروم
    devices:
      - /dev/snd:/dev/snd # دسترسی مستقیم به دیوایس‌های کارت صدا در لینوکس
    volumes:
      # Mount the config file
      - ./egress.yaml:/etc/egress.yaml
      # Mount the folder where you want recordings saved
      - /home/recording:/out

    # the entrypoint file not find config file do not use command command: --config /etc/egress.yaml
    # the entry point not append --config  yaml in last line of entrypoint.sh!
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
      - EGRESS_LOG_LEVEL=debug
    network_mode: host
    depends_on:
      - redis

